@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bewitchment.common.core.capability.transformation;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;