@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bewitchment.client.handler;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;