@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bewitchment.common.core.capability.divination;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;