@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.witchcraft.common.crafting;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;